# Generated by Django 6.0.3 on 2026-03-22 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "favoritas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="receitas_favoritas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredientes",
                    models.ManyToManyField(
                        related_name="receitas", to="receita.ingrediente"
                    ),
                ),
            ],
        ),
    ]
